config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    devise_for :users
    root to: "foods#index"
    resources :categories
    resources :foods
    resources :order_addresses
    resources :order_items
    resources :users
    resources :orders, only: [:edit, :update, :destroy, :index]
    resources :reviews, only: [:new, :create]
    scope "/orders" do
      get "cart", to: "orders#show"
      post "accept", to: "orders#accept"
      post "add_address", to: "orders#create_address"
      post "confirm", to: "orders#confirm"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :foods, dependent: :destroy
  validates :name, presence: true
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :category
  has_many :images, dependent: :destroy
  has_many :order_items, dependent: :destroy
  has_many :reviews
  accepts_nested_attributes_for :images
  validates :name, presence: true
  validates :price, presence: true
  validates :description, presence: true, length: {minimum:Settings.minimum_length_description, maximum:Settings.maximum_length_description}
  scope :by_price, ->(first_price, last_price) do
    where("price BETWEEN ? AND ?", first_price, last_price)
  end
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :food
  mount_uploader :image, ImageUploader
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy
  enum status: { declined: -1, init: 0, created: 1, accepted: 2, confirmed: 3, reviewed: 4}

  def sum
    self.totalprice = OrderItem.joins(:food).where(order_items: {order_id: self.id}).sum('order_items.quantity * foods.price')
    self.save
  end
end

app/models/order_address.rb
class OrderAddress < ApplicationRecord
  belongs_to :user
  validates :address, presence: true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :user
  belongs_to :order
  belongs_to :food
  after_save :sum

  def sum
    self.order.sum
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :food
  validates :rate, presence: true
  validates :comment, length: {maximum:Settings.maximum_length_comment}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :order_addresses
  has_many :order_items
  has_many :orders
  has_many :reviews

  def add_using_address(order_address)
    self.order_addresses.update_all is_using: false
    order_address.is_using = true
    order_address.save
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :find_food, only: [:show, :destroy]
  before_action :require_admin, only: [:create, :destroy]

  def new
    @food = Food.new
    @food.images.build
  end

  def create
    @food = Food.new(food_params)
    if @food.save
      flash[:notice] = t 'flash.food.success'
      redirect_to root_url
    else
      render 'new'
    end
  end

  def index
    @q = Food.ransack(params[:q])
    @foods = @q.result
    if params[:q].present? && !params[:q][:price].empty?
      range = Settings.range_price["range_#{params[:q][:price]}"]
      @foods = @foods.by_price(range.first, range.last)
    end
    @foods = @foods.page(params[:page] || Settings.paginate.default_page).per(params[:page_size] || Settings.paginate.default_per_page)
  end

  def show
    @reviews = @food.reviews.all.order(created_at: :desc)
  end

  def destroy
    if @food.destroy
      flash[:success] = t 'flash.food.delete'
    else
      flash[:notice] = t 'flash.food.notdelete'
    end
    redirect_to root_path
  end

  private

  def food_params
    params.require(:food).permit :name, :description, :price, :category_id, images_attributes: [:image]
  end

  def find_food
    @food = Food.find_by id: params[:id]
    return if @food.present?

    flash[:danger] = t 'flash.food.notfound'
    redirect_to root_url
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @foods = Food.all.order(name: :asc)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :find_order, only: [:edit, :show, :update]
  before_action :require_admin, only: [:index]

  def show
  end

  def index
    @orders = Order.all.order(order_time: :desc)
  end

  def edit
    @order_address = OrderAddress.new
    @order_addresses = current_user.order_addresses
  end

  def create_address
    @order_address = current_user.order_addresses.build(address_params)
    respond_to do |format|
      if @order_address.save
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @order_address.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    if @order.update(order_params)
      flash[:notice] = t('flash.order.success')
      redirect_to user_path(current_user)
    else
      render 'edit'
    end
  end

  def accept
    @order = Order.find_by id: params[:id]
    if @order.update(params.permit(:status))
      flash[:notice] = t('flash.order.success')
      redirect_to orders_path
    else
      render 'edit'
    end
  end

  def confirm
    @order = current_user.orders.find(params[:id])
    if @order.update(params.permit(:status))
      flash[:notice] = t('flash.order.success')
      redirect_to user_path(current_user)
    else
      render 'users/show'
    end
  end

  private

  def find_order
    @order = current_user.orders.find_by status: :init
  end

  def order_params
    params.require(:order).permit(:address, :status, :order_time)
  end

  def require_admin
    redirect_to root if !current_user.admin?
  end

  def address_params
    params.require(:order_address).permit(:address, :is_using)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @order = current_user.orders.find(params[:order])
  end

  def create
    @order = current_user.orders.find(params[:order_id])
    @reviews = Array.new(@order.order_items.length) { current_user.reviews.new }
    @reviews.each_with_index do |review,i|
      review.food = @order.order_items[i].food
      review.rate = params[:rate]
      review.comment = params[:comment]
      review.save
    end
    @order.status = "reviewed"
    @order.save
    flash[:notice] = t 'flash.success'
    redirect_to user_path(current_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @orders = current_user.orders.order(order_time: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_addresses_helper.rb
module OrderAddressesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/_foods.html.erb
<div class="container">
  <% @foods.each do |food| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-2">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <div class="h3"> <%= link_to food.name, food_path(food) %></div>
            <div class="mt-2"> <%= link_to food.category.name, category_path(food.category), class: "badge badge-pill badge-info mr-1" %> </div>
          </div>
          <div class="card-body">
            <p class="card-text"><%= t '.description'%>: <%= food.description %></p>
            <p class="card-text"><%= t '.price'%>: <%= food.price %></p>
            <% unless food.images.length == 0 %>
              <img src= "<%= food.images.first.image.url %>" width="600px"/>
            <% end %>
            <div class = "mt-4">
              <% if user_signed_in? && current_user.admin? %>
                <%= link_to t('foods.index.delete'), food_path(food), class: "btn btn-outline-danger", method: :delete, data: {confirm: t('flash.sure')} %>
              <% end %>
            </div>
            <div class = "mt-4">
              <% @order_item = OrderItem.new %>
              <% if user_signed_in? && !current_user.admin? %>
                <%= form_with(model: @order_item, class: "shadow p-3 mb-3 rounded", local: true) do |f| %>
                  <div class="form-group row">
                    <%= f.label :quantity, t('.quantity'), class: "col-2 col-form-label text-dark" %>
                    <div class="col-10">
                      <%= f.text_field :quantity, class: "form-control shadow rounded" %>
                    </div>
                  </div>
                  <%= f.hidden_field :food_id, value: food.id %>
                  <div class="form-group row justify-content-center">
                    <%= f.submit class: "btn btn-outline-dark btn-lg" %>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/foods/index.html.erb
<div class="text-center mt-4">
  <%= search_form_for @q do |f| %>
    <%= f.label :name_cont, t('.name') %>
    <%= f.search_field :name_cont %>
    <%= sort_link(@q, :price, t('.price'), default_order: :asc , class: "link-light")%>
    <%= sort_link(@q, :created_at, t('.latest'), default_order: :desc , class: "link-light")%>
    <%= f.select :price,
      options_for_select([[t('.chooseprice'),nil],[t('.price1'),'1'],[t('.price2'),'2'],[t('.price3'),'3']], params[:price]),
      {}, { :class => 'span3 controls controls-row' } %>
    <%= f.submit class: "btn btn-outline-success my-2 my-sm-0"%>
  <% end %>
</div>
<h1 class="text-center mt-4"><%= t('.listing') %></h1>
<div class="container">
  <div class="row justify-content-md-center">
    <div class="flickr_pagination">
      <%= paginate @foods %>
    </div>
  </div>
</div>
<%= render 'foods' %>
<div class="container">
  <div class="row justify-content-md-center">
    <div class="flickr_pagination">
      <%= paginate @foods %>
    </div>
  </div>
</div>

app/views/foods/new.html.erb
<h1 class="text-center mt-4">Create a new food</h1>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <div class ="shadow p-3 mb-3 bg-info rounded" >
        <%= form_for @food do |f| %>
          <div class="form-group row">
            <%= f.label :name, t('.name'), class: "col-2 col-form-label text-light" %>
            <div class="col-10">
              <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>
            </div>
          </div>
          <div class="form-group row">
            <%= f.label :description, t('.description'), class: "col-2 col-form-label text-light" %>
            <div class="col-10">
              <%= f.text_field :description, class: "form-control shadow rounded", placeholder: "Enter a description" %>
            </div>
          </div>
          <div class="form-group row">
            <%= f.label :price, t('.price'), class: "col-2 col-form-label text-light" %>
            <div class="col-10">
              <%= f.text_field :price, class: "form-control shadow rounded", placeholder: "Enter a price" %>
            </div>
          </div>
          <div class="form-group row">
            <%= f.label :category, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
              <%= f.collection_select(:category_id, Category.all, :id, :name, { multiple: true, size: 4, class: "custom-select shadow rounded" }) %>
            </div>
          </div>
          <%= f.fields_for :images do |p| %>
            <div class="form-group row">
              <span class="image col-10">
                <%= p.file_field :image %>
              </span>
            </div>
          <% end %>
          <%= f.fields_for :images do |p| %>
          <div class="form-group row">
            <span class="image col-10">
              <%= p.file_field :image %>
            </span>
          </div>
          <% end %>
          <div class="form-group row justify-content-center">
            <%= f.submit class: "btn btn-outline-light btn-lg" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/foods/show.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-2">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          <div class="h3"> <%= link_to @food.name, food_path(@food) %></div>
            <div class="mt-2"> <%= link_to @food.category.name, category_path(@food.category), class: "badge badge-pill badge-info mr-1" %> </div>
          </div>
          <div class="card-body">
            <p class="card-text"><%= t '.description'%>: <%= @food.description %></p>
            <p class="card-text"><%= t '.price'%>: <%= @food.price %></p>
            <% @food.images.each do |img|%>
              <img src= "<%= img.image.url %>" width="600px" class="mt-4"/>
            <% end %>
          </div>
      </div>
    </div>
  </div>
  <div class="row justify-content-md-center">
    <div class="col-8 mt-2">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          <div class="h3"> <%= t '.review' %> </div>
        </div>
      </div>
    </div>
  </div>
  <% @reviews.each do |review| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-2">
        <div class="card shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <div class="h5"><%= review.user.email %></div>
          </div>
          <div class="card-body">
            <p class="card-text"><%= t '.rate' %> : <%= review.rate %></p>
            <p class="card-text"><%= t '.comment' %> : <%= review.comment %></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/orders/_order_address.html.erb
<div class="col-10">
  <%= radio_button_tag "address", order_address.id, order_address.is_using? %>
  <%= order_address.address %>
</div>

app/views/orders/create_address.js.erb
var address = document.querySelector("#addresses");
address.insertAdjacentHTML("beforeend", "<%= j render partial: "order_address", locals: {order_address: @order_address} %>");

app/views/orders/edit.html.erb
<h1 class="text-center mt-4"><%= t('.title') %></h1>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <div class ="shadow p-3 mb-3 bg-info rounded text-light" >
        <%= form_for(:order_address, url: add_address_path, method: :post, remote: true) do |f| %>
          <h4><%= t('.newaddress') %></h4>
          <div class="form-group row">
            <%= f.label :address, t(".address"), class: "col-2 col-form-label text-light" %>
            <div class="col-10">
              <%= f.text_field :address, class: "form-control shadow rounded" %>
            </div>
          </div>
          <%= f.label :is_using, class: "checkbox inline ml-4" do %>
            <%= f.check_box :is_using, {:checked=>true}  %>
            <span> <%= t('.address_using') %> </span>
          <% end %>
          <div class="form-group row justify-content-center">
            <%= f.submit class: "btn btn-outline-light btn-lg" %>
          </div>
        <% end %>

        <%= form_for @order do |f| %>
          <h4><%= t('.chooseaddress') %></h4>
          <div id="addresses">
            <%= render partial: "order_address", collection: @order_addresses, as: "order_address" %>
          </div>
          <%= f.hidden_field :status, value: 'created' %>
          <%= f.hidden_field :order_time, value: Time.now %>
          <div class="form-group row justify-content-center">
            <%= f.submit class: "btn btn-outline-light btn-lg" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/orders/index.html.erb
<div class="container">
  <% @orders.each do |order| %>
    <% if order.status != "init" %>
      <div class="row justify-content-md-center">
        <div class="col-8 mt-2">
          <div class="card text-center shadow mb-5 bg-white rounded">
            <p class="card-header font-italic bg-info font-weight-bold"> <%= t('.status') %> : <%= order.status %></p>
            <p class="card-header font-italic"> <%= order.order_time %></p>
            <p class="card-header font-italic"> <%= order.address %></p>
            <% order.order_items.each do |order_item| %>
              <div class="card-header font-italic">
                <div class="h3"> <%= link_to order_item.food.name, food_path(order_item.food) %></div>
              </div>
              <div class="card-body">
                <p class="card-text"><%= t('.price')%>: <%= order_item.food.price %></p>
                <p class="card-text"><%= t('.quantity')%>: <%= order_item.quantity %></p>
              </div>
            <% end %>
            <h3 class="card-header font-italic"><%= t('total') %> : <%= order.totalprice %></h3>
            <% if order.status == "created" %>
            <div class="form-group row justify-content-center">
              <%= form_with(class: "shadow p-3 mb-3 rounded", local: true, :url => { :action => :accept, :id => order}) do |f| %>
                <%= f.hidden_field :status, value: 'accepted' %>
                  <%= f.submit "Accept", class: "btn btn-outline-dark btn-lg" %>
              <% end %>
              <%= form_with(class: "shadow p-3 mb-3 rounded", local: true, :url => { :action => :accept, :id => order}) do |f| %>
                <%= f.hidden_field :status, value: 'declined' %>
                  <%= f.submit "Decline", class: "btn btn-outline-dark btn-lg" %>
              <% end %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/orders/show.html.erb
<div class="container">
  <% @order.order_items.each do |order_item| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-2">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <div class="h3"> <%= link_to order_item.food.name, food_path(order_item.food) %></div>
          </div>
          <div class="card-body">
            <p class="card-text"><%= t('.price')%>: <%= order_item.food.price %></p>
            <p class="card-text"><%= t('.quantity')%>: <%= order_item.quantity %></p>
            <p class="card-text"><%= link_to t('.delete'), order_item_path(order_item), class: "btn btn-outline-danger", method: :delete, data: {confirm: t('flash.sure')} %></p>
          </div>
        </div>
      </div>
    </div>
  <%end%>
  <h3><%= t('.total') %> : <%= @order.totalprice %></h3>
  <% if @order.status == "init" %>
    <%= link_to t('.buy'), edit_order_path(@order), class: "btn btn-outline-danger" %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <% @orders.each do |order| %>
    <% if order.status != "init" %>
      <div class="row justify-content-md-center">
        <div class="col-8 mt-2">
          <div class="card text-center shadow mb-5 bg-white rounded">
            <p class="card-header font-italic bg-info font-weight-bold"> <%= t('.status') %> : <%= order.status %></p>
            <p class="card-header font-italic"> <%= order.order_time %></p>
            <p class="card-header font-italic"> <%= order.address %></p>
            <% order.order_items.each do |order_item| %>
              <div class="card-header font-italic">
                <div class="h3"> <%= link_to order_item.food.name, food_path(order_item.food) %></div>
              </div>
              <div class="card-body">
                <p class="card-text"><%= t('.price')%>: <%= order_item.food.price %></p>
                <p class="card-text"><%= t('.quantity')%>: <%= order_item.quantity %></p>
              </div>
            <% end %>
            <h3 class="card-header font-italic"><%= t('total') %> : <%= order.totalprice %></h3>
            <% if order.status == "accepted" %>
            <div class="form-group row justify-content-center">
              <%= form_with(class: "shadow p-3 mb-3 rounded", local: true, :url => {:controller => :orders, :action => :confirm, :id => order}) do |f| %>
                <%= f.hidden_field :status, value: 'confirmed' %>
                  <%= f.submit "I received the food", class: "btn btn-outline-dark btn-lg" %>
              <% end %>
            </div>
            <% end %>
            <% if order.status == "confirmed" %>
            <div class="form-group row justify-content-center">
              <%= link_to "Review", new_review_path(:order => order.id) %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>