config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    devise_for :users
    root to: "foods#index"
    resources :categories
    resources :foods
    resources :order_addresses
    resources :order_items
    resources :users
    resources :orders, only: [:edit, :update, :destroy, :index]
    resources :reviews, only: [:new, :create]
    scope "/orders" do
      get "cart", to: "orders#show"
      post "accept", to: "orders#accept"
      post "add_address", to: "orders#create_address"
      post "confirm", to: "orders#confirm"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :foods, dependent: :destroy
  validates :name, presence: true
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :category
  has_many :images, dependent: :destroy
  has_many :order_items, dependent: :destroy
  has_many :reviews
  accepts_nested_attributes_for :images
  validates :name, presence: true
  validates :price, presence: true
  validates :description, presence: true, length: {minimum:Settings.minimum_length_description, maximum:Settings.maximum_length_description}
  scope :by_price, ->(first_price, last_price) do
    where("price BETWEEN ? AND ?", first_price, last_price)
  end
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :food
  mount_uploader :image, ImageUploader
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy
  enum status: { declined: -1, init: 0, created: 1, accepted: 2, confirmed: 3, reviewed: 4}

  def sum
    self.totalprice = OrderItem.joins(:food).where(order_items: {order_id: self.id}).sum('order_items.quantity * foods.price')
    self.save
  end
end

app/models/order_address.rb
class OrderAddress < ApplicationRecord
  belongs_to :user
  validates :address, presence: true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :user
  belongs_to :order
  belongs_to :food
  after_save :sum

  def sum
    self.order.sum
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :food
  validates :rate, presence: true
  validates :comment, length: {maximum:Settings.maximum_length_comment}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :order_addresses
  has_many :order_items
  has_many :orders
  has_many :reviews

  def add_using_address(order_address)
    self.order_addresses.update_all is_using: false
    order_address.is_using = true
    order_address.save
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :find_food, only: [:show, :destroy]
  before_action :require_admin, only: [:create, :destroy]

  def new
    @food = Food.new
    @food.images.build
  end

  def create
    @food = Food.new(food_params)
    if @food.save
      flash[:notice] = t 'flash.food.success'
      redirect_to root_url
    else
      render 'new'
    end
  end

  def index
    @q = Food.ransack(params[:q])
    @foods = @q.result
    if params[:q].present? && !params[:q][:price].empty?
      range = Settings.range_price["range_#{params[:q][:price]}"]
      @foods = @foods.by_price(range.first, range.last)
    end
    @foods = @foods.page(params[:page] || Settings.paginate.default_page).per(params[:page_size] || Settings.paginate.default_per_page)
  end

  def show
    @reviews = @food.reviews.all.order(created_at: :desc)
  end

  def destroy
    if @food.destroy
      flash[:success] = t 'flash.food.delete'
    else
      flash[:notice] = t 'flash.food.notdelete'
    end
    redirect_to root_path
  end

  private

  def food_params
    params.require(:food).permit :name, :description, :price, :category_id, images_attributes: [:image]
  end

  def find_food
    @food = Food.find_by id: params[:id]
    return if @food.present?

    flash[:danger] = t 'flash.food.notfound'
    redirect_to root_url
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @foods = Food.all.order(name: :asc)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @orders = current_user.orders.order(order_time: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">HB FOOD</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to t("nav.home"), root_url, class: "nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to t('nav.categories'), categories_path, class: "nav-link"%>
      </li>
      <% if user_signed_in? && current_user.admin? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= t('managepage') %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to t('nav.newcategory'), new_category_path, class: "dropdown-item"%>
            <%= link_to t('nav.newfood'), new_food_path, class: "dropdown-item"%>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to "Orders", orders_path, class: "nav-link"%>
        </li>
      <% end %>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to t('nav.logout'), destroy_user_session_path,:method => :delete , class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Cart", cart_path, class: "nav-link"%>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to t('.login'), new_user_session_path, class: "nav-link"%>
        </li>
      <% end %>
      <% if user_signed_in? && !current_user.admin?%>
      <li class="nav-item">
        <%= link_to t('nav.myorders'), user_path(current_user), class: "nav-link"%>
      </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodOrdering</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div id="page-content"></div>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>